name: iOS Build and Upload to TestFlight

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: iOS Build Action
        uses: yukiarrr/ios-build-action@v1.11.2
        with:
          project-path: helloworld.xcodeproj
          p12-base64: ${{ secrets.P12_BASE64 }}
          mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
          code-signing-identity: 'iPhone Distribution'
          certificate-password: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
          team-id: ${{ secrets.TEAM_ID }}

      - name: Upload to TestFlight
        run: |
          xcrun altool --upload-app -f helloworld.ipa -t ios -u ${{ secrets.APP_ID }} -p ${{ secrets.APP_SPECIFIC_PASSWORD }}
